# docker-compose.yml

version: '3.8'
services:
  app: 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://postgres:lNiMwWazYVb6aM5t7Zrv@containers-us-west-150.railway.app:5772/railway
      - PORT=3000
      - PRISMA_QUERY_ENGINE_BINARY=debian-openssl-1.1.x

  web:
    build: .
    volumes:
      - .:/app
      - /app/node_modules # prevents overwriting